deps-run: &deps-install
  name: Install Python dependencies and PlasmaPy
  command: |
    pip install --user -r requirements/automated-documentation-tests.txt | cat
    pip install --user . | cat

html-run: &doc-html
  name: Build HTML documentation
  command: python setup.py build_docs -w

latex-run: &doc-latex
  name: Build LaTeX documentation
  command: python setup.py build_docs -b latex -w

version: 2
jobs:
  test-html:
    docker:
      - image: plasmapy/documentation-builder:latest
    steps:
      - checkout
      - run: *deps-install
      - run: *doc-html
      - store_artifacts:
          path: docs/_build/html
      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/docs/_build/html/index.html"; echo $DOCS_URL
      - run: *doc-latex

workflows:
  version: 2
  test-documentation:
    jobs:
      - test-html

notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
