name: plasmapy

channels:
  - astropy

dependencies:
  - python=3.6
  - numpy
  - scipy
  - astropy
  - cython
  - pip:
    - numpydoc
    - pytest
    - mpmath
    - roman
    - h5py
    - lmfit
    - matplotlib
    - sphinx
    - sphinx-gallery
    - sphinx-automodapi
    - pillow
    - colorama
    - sphinx_rtd_theme
